import { ChangeDetectionStrategy, Component } from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  lucideMap, lucidePlus, lucideCheck, lucideCircle, lucideClock,
  lucideCalendar, lucideEdit, lucideTrash, lucideArrowRight,
  lucideTarget, lucideZap, lucideFlag,
} from '@ng-icons/lucide';

interface RoadmapStep {
  phase: string;
  title: string;
  description: string;
  dueDate: string;
  status: 'completed' | 'in-progress' | 'pending';
  tasks: { label: string; done: boolean }[];
}

@Component({
  selector: 'app-roadmaps',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIconComponent],
  providers: [provideIcons({
    lucideMap, lucidePlus, lucideCheck, lucideCircle, lucideClock,
    lucideCalendar, lucideEdit, lucideTrash, lucideArrowRight,
    lucideTarget, lucideZap, lucideFlag,
  })],
  template: `
    <div class="space-y-5">

      <!-- Header -->
      <div class="flex items-center justify-between">
        <div>
          <h2 class="text-lg font-bold" style="color:var(--text-primary); letter-spacing:-0.02em;">Roadmaps</h2>
          <p class="text-xs mt-0.5" style="color:var(--text-secondary);">Track your startup journey milestones</p>
        </div>
        <div class="flex items-center gap-2">
          <button class="text-xs font-semibold rounded-lg border cursor-pointer"
            style="background:var(--surface); color:var(--text-body); border-color:var(--border); padding:7px 14px;">
            <ng-icon name="lucideCalendar" [size]="'13'" style="display:inline; margin-right:4px;" />
            Calendar View
          </button>
          <button class="flex items-center gap-1.5 text-xs font-semibold rounded-lg border-none cursor-pointer"
            style="background:linear-gradient(135deg,#7C3AED,#3B82F6); color:#fff; padding:8px 16px;">
            <ng-icon name="lucidePlus" [size]="'14'" />
            Add Step
          </button>
        </div>
      </div>

      <!-- Overall progress -->
      <div class="rounded-xl border p-5"
        style="background:linear-gradient(135deg,#0B0F2A,#1E1B4B); border-color:#312E81; box-shadow:0 4px 20px rgba(11,15,42,0.2);">
        <div class="flex items-center justify-between mb-4">
          <div>
            <h3 class="text-base font-bold" style="color:#fff;">TechFlow — Seed Stage Roadmap</h3>
            <p class="text-xs mt-0.5" style="color:#A5B4FC;">Generated by AI mentor · Updated Apr 4, 2026</p>
          </div>
          <div class="flex items-center gap-1.5 text-xs font-semibold rounded-lg"
            style="background:rgba(255,255,255,0.1); color:#fff; padding:6px 12px;">
            <ng-icon name="lucideZap" [size]="'13'" style="color:#FBBF24;" />
            AI-Generated
          </div>
        </div>
        <div class="flex items-center justify-between mb-2">
          <span class="text-xs" style="color:#A5B4FC;">Overall Progress</span>
          <span class="text-sm font-bold" style="color:#fff;">{{ overallProgress }}%</span>
        </div>
        <div style="height:8px; background:rgba(255,255,255,0.1); border-radius:99px; overflow:hidden;">
          <div style="height:100%; border-radius:99px; background:linear-gradient(90deg,#818CF8,#60A5FA); transition:width 0.8s cubic-bezier(.4,0,.2,1);"
            [style.width.%]="overallProgress">
          </div>
        </div>
        <div class="flex items-center gap-6 mt-3">
          <div class="flex items-center gap-1.5">
            <div style="width:8px;height:8px;border-radius:50%;background:#34D399;"></div>
            <span class="text-xs" style="color:#A5B4FC;">{{ completedSteps }} Completed</span>
          </div>
          <div class="flex items-center gap-1.5">
            <div style="width:8px;height:8px;border-radius:50%;background:#60A5FA;"></div>
            <span class="text-xs" style="color:#A5B4FC;">1 In Progress</span>
          </div>
          <div class="flex items-center gap-1.5">
            <div style="width:8px;height:8px;border-radius:50%;background:rgba(255,255,255,0.2);"></div>
            <span class="text-xs" style="color:#A5B4FC;">{{ pendingSteps }} Pending</span>
          </div>
        </div>
      </div>

      <!-- Roadmap timeline -->
      <div class="grid gap-4" style="grid-template-columns:1fr;">
        @for (step of steps; track step.title; let i = $index) {
          <div class="flex gap-4">
            <!-- Timeline indicator -->
            <div class="flex flex-col items-center flex-shrink-0" style="width:40px;">
              <div class="flex items-center justify-center rounded-full"
                style="width:36px; height:36px; border:2px solid;"
                [style.background]="step.status === 'completed' ? '#059669' : step.status === 'in-progress' ? '#3B82F6' : '#F3F4F6'"
                [style.border-color]="step.status === 'completed' ? '#059669' : step.status === 'in-progress' ? '#3B82F6' : '#D1D5DB'">
                @if (step.status === 'completed') {
                  <ng-icon name="lucideCheck" [size]="'16'" style="color:#fff;" />
                } @else if (step.status === 'in-progress') {
                  <ng-icon name="lucideZap" [size]="'14'" style="color:#fff;" />
                } @else {
                  <ng-icon name="lucideCircle" [size]="'14'" style="color:#D1D5DB;" />
                }
              </div>
              @if (i < steps.length - 1) {
                <div style="width:2px; flex:1; min-height:20px; margin-top:4px;"
                  [style.background]="step.status === 'completed' ? '#059669' : '#E5E9F5'">
                </div>
              }
            </div>

            <!-- Step card -->
            <div class="flex-1 rounded-xl border mb-4 overflow-hidden transition-all hover:shadow-sm"
              style="box-shadow:0 1px 4px rgba(11,15,42,0.04);"
              [style.background]="step.status === 'in-progress' ? '#FAFBFF' : '#fff'"
              [style.border-color]="step.status === 'in-progress' ? '#BFDBFE' : '#E5E9F5'">
              <div class="flex items-start justify-between px-5 py-4">
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2 mb-1">
                    <span class="text-xs font-semibold px-1.5 py-0.5 rounded"
                      style="background:var(--badge-purple-bg); color:#7C3AED;">{{ step.phase }}</span>
                    <span class="text-xs font-medium px-1.5 py-0.5 rounded-full"
                      [style.background]="step.status === 'completed' ? '#D1FAE5' : step.status === 'in-progress' ? '#DBEAFE' : '#F3F4F6'"
                      [style.color]="step.status === 'completed' ? '#065F46' : step.status === 'in-progress' ? '#1E40AF' : '#6B7A99'">
                      {{ step.status === 'in-progress' ? 'In Progress' : step.status === 'completed' ? 'Completed' : 'Pending' }}
                    </span>
                  </div>
                  <h4 class="text-sm font-bold mb-1" style="color:var(--text-primary);">{{ step.title }}</h4>
                  <p class="text-xs leading-relaxed" style="color:var(--text-secondary);">{{ step.description }}</p>
                </div>
                <div class="flex items-center gap-2 ml-4 flex-shrink-0">
                  <div class="flex items-center gap-1 text-xs" style="color:var(--text-muted);">
                    <ng-icon name="lucideCalendar" [size]="'11'" />
                    {{ step.dueDate }}
                  </div>
                  <button class="flex items-center justify-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                    style="width:26px; height:26px; background:transparent; border:none; cursor:pointer; color:var(--text-muted);"
                    [attr.aria-label]="'Edit ' + step.title">
                    <ng-icon name="lucideEdit" [size]="'13'" />
                  </button>
                </div>
              </div>

              <!-- Tasks checklist -->
              <div style="border-top:1px solid var(--border-subtle); padding:12px 20px;">
                <div class="flex flex-wrap gap-x-6 gap-y-1.5">
                  @for (task of step.tasks; track task.label) {
                    <div class="flex items-center gap-1.5">
                      <div class="flex items-center justify-center rounded flex-shrink-0"
                        style="width:14px; height:14px;"
                        [style.background]="task.done ? '#059669' : '#F3F4F6'"
                        [style.border]="task.done ? 'none' : '1.5px solid #D1D5DB'">
                        @if (task.done) {
                          <ng-icon name="lucideCheck" [size]="'9'" style="color:#fff;" />
                        }
                      </div>
                      <span class="text-xs"
                        [style.color]="task.done ? '#9CA3AF' : '#374151'"
                        [style.text-decoration]="task.done ? 'line-through' : 'none'">
                        {{ task.label }}
                      </span>
                    </div>
                  }
                </div>
              </div>
            </div>
          </div>
        }
      </div>
    </div>
  `,
})
export class RoadmapsComponent {
  protected readonly steps: RoadmapStep[] = [
    {
      phase: 'Phase 1', title: 'Validate Product-Market Fit', dueDate: 'Feb 28, 2026', status: 'completed',
      description: 'Conduct customer discovery interviews, build MVP, and gather initial traction metrics to validate the core value proposition.',
      tasks: [
        { label: '50 customer interviews', done: true },
        { label: 'MVP launched',           done: true },
        { label: '100 beta users',         done: true },
        { label: 'NPS score > 40',         done: true },
      ],
    },
    {
      phase: 'Phase 2', title: 'Build Core Team & Legal Structure', dueDate: 'Mar 31, 2026', status: 'completed',
      description: 'Formalize the company, recruit key technical and business co-founders, and establish governance foundations.',
      tasks: [
        { label: 'Company registered (SARL)', done: true },
        { label: 'CTO recruited',             done: true },
        { label: 'Shareholder agreement',     done: true },
        { label: 'Startup label obtained',    done: false },
      ],
    },
    {
      phase: 'Phase 3', title: 'Fundraising — Pre-Seed Round', dueDate: 'Apr 30, 2026', status: 'in-progress',
      description: 'Prepare investor materials, pitch to angel network, and close a pre-seed round to fund 12 months of growth.',
      tasks: [
        { label: 'Pitch deck finalized',         done: true  },
        { label: 'Financial model built',        done: true  },
        { label: '20 investor meetings',         done: false },
        { label: 'Term sheet signed',            done: false },
        { label: 'Due diligence completed',      done: false },
      ],
    },
    {
      phase: 'Phase 4', title: 'Scale Product & User Acquisition', dueDate: 'Jun 30, 2026', status: 'pending',
      description: 'Use raised capital to scale the product, launch marketing campaigns, and hit 1,000 paying customers.',
      tasks: [
        { label: 'Hire 2 engineers',       done: false },
        { label: 'Launch growth campaigns', done: false },
        { label: '500 paying users',       done: false },
        { label: 'MRR of $15K',           done: false },
      ],
    },
    {
      phase: 'Phase 5', title: 'Seed Round & Market Expansion', dueDate: 'Oct 31, 2026', status: 'pending',
      description: 'Close seed round, expand to 2 additional markets, and build partnerships with key enterprise customers.',
      tasks: [
        { label: 'Seed round closed ($300K+)', done: false },
        { label: 'Expand to 2nd market',       done: false },
        { label: '3 enterprise pilots',        done: false },
      ],
    },
  ];

  protected get overallProgress(): number {
    const totalTasks = this.steps.reduce((sum, s) => sum + s.tasks.length, 0);
    const doneTasks = this.steps.reduce((sum, s) => sum + s.tasks.filter(t => t.done).length, 0);
    return Math.round((doneTasks / totalTasks) * 100);
  }

  protected get completedSteps(): number {
    return this.steps.filter(s => s.status === 'completed').length;
  }

  protected get pendingSteps(): number {
    return this.steps.filter(s => s.status === 'pending').length;
  }
}
